# Generated by Django 4.1.7 on 2023-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cardNumber', models.IntegerField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('registeredDate', models.DateTimeField(auto_now_add=True)),
                ('imageCount', models.IntegerField()),
            ],
            options={
                'ordering': ['-registeredDate'],
            },
        ),
    ]
